// Database types for Supabase tables

export interface User {
  id: string;
  clerk_user_id: string;
  email: string;
  name: string | null;
  timezone: string;
  created_at: string;
  updated_at: string;
}

export interface Idea {
  id: string;
  user_id: string;
  title: string;
  description: string | null;
  bullets: string[];
  external_links: string[];
  status: 'pending' | 'expanded' | 'archived';
  priority_score: number;
  last_evaluated_at: string | null;
  times_evaluated: number;
  created_at: string;
  updated_at: string;
}

export interface Credential {
  id: string;
  user_id: string;
  provider: 'openai' | 'anthropic' | 'github' | 'twitter' | 'replicate';
  encrypted_value: string;
  is_active: boolean;
  validation_status: 'valid' | 'invalid' | 'not_checked';
  created_at: string;
  updated_at: string;
}

export interface Execution {
  id: string;
  user_id: string;
  selected_idea_id: string | null;
  judge_reasoning: string | null;
  judge_score: number | null;
  format_chosen: 'blog_post' | 'twitter_thread' | 'github_repo' | 'image' | null;
  format_reasoning: string | null;
  status: 'running' | 'completed' | 'failed' | 'partial';
  error_message: string | null;
  error_step: string | null;
  tokens_used: number;
  duration_seconds: number | null;
  started_at: string;
  completed_at: string | null;
}

export interface Output {
  id: string;
  execution_id: string;
  user_id: string;
  idea_id: string | null;
  format: 'blog_post' | 'twitter_thread' | 'github_repo' | 'image';
  content: any; // JSONB
  published: boolean;
  publication_url: string | null;
  publication_metadata: any; // JSONB
  created_at: string;
  published_at: string | null;
}

export interface BlogPost {
  id: string;
  output_id: string | null;
  user_id: string;
  title: string;
  slug: string;
  markdown_content: string;
  html_content: string;
  meta_description: string | null;
  tags: string[];
  is_public: boolean;
  published_at: string | null;
  created_at: string;
  updated_at: string;
}

// Input types for creating/updating records
export interface CreateIdeaInput {
  content: string; // The raw idea - just what the user types
  title?: string;  // Optional - will be generated by AI if not provided
  description?: string;
  bullets?: string[];
  external_links?: string[];
}

export interface UpdateIdeaInput {
  title?: string;
  description?: string;
  bullets?: string[];
  external_links?: string[];
  status?: 'pending' | 'expanded' | 'archived';
}
